### ISSUE TITLE
test share mutex abort in gcc 4.8.4

### ISSUE THREAD

**Issue by zhangxc11** [ParrotsDL/CLUE#8]
when compiling test_shared_mutex use gcc 4.8.4 on ubuntu, it will abort with following error message
```
Testing exclusive locking ...
terminate called after throwing an instance of 'std::system_error'
  what():  Enable multithreading to use std::thread: Operation not permitted
[1]    30666 abort (core dumped)  ./bin/test_shared_mutex
```
This is similar to https://stackoverflow.com/questions/19463602/compiling-multithread-code-with-g 

and can be fixed by add a line in CMakeLists.txt
```
SET( CMAKE_EXE_LINKER_FLAGS  "-Wl,--no-as-needed ${CMAKE_EXE_LINKER_FLAGS}")
```

**Comment by lindahua** [comment]
Can you make the modification and test it with gcc 4.8.4? I can merge the PR if this is confirmed to work, as I don't have gcc 4.8.4 at hand.

**Comment by zhangxc11** [comment]
done in #9
